version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "7000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: c_web_server
    restart: always
    ports:
      - "7071:7071"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "gcc /app/server.c -o /app/server -lmicrohttpd -lmariadb -I/usr/include/mariadb && /app/server"]

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "7002:8080"

volumes:
  db_data:
